version: '3.8'

volumes:
  pgdata:

services:
  db:
    image: postgres
    restart: always
    env_file:
      - '.env'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
