version: '3.8'

volumes:
  pgdata:
  minio-data:

services:
  db:
    image: postgres
    restart: always
    env_file:
      - '.env'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: on-failure
    env_file:
      - '.env'
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}'
      - '${MINIO_PORT_UI}:${MINIO_PORT_UI}'
    volumes:
      - minio-data:/data
    command: server /data --address ":${MINIO_PORT}" --console-address ":${MINIO_PORT_UI}"
